FROM python:3.9-slim-buster

# Set environment variables
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# Set working directory
WORKDIR .

# Copy requirements file
COPY deployment/requirements.txt .

# Install dependencies
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy rest of the app
COPY source/ source/

# Expose port for the API
EXPOSE 8000

# Run the command to start the API
CMD ["uvicorn", "source.main:app", "--host", "0.0.0.0", "--port", "8000"]