name: Push

on:
  push:
    branches:
    - master
    paths:
    - '**/*.py'
    - '.github/workflows/push.yaml'

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: install python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: install dependencies
      run: |
        pip install --upgrade pip
        pip install flake8

    - name: lint
      working-directory: services/nlp_api
      run: |
        python -m flake8 source/

  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: install python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: install dependencies
      run: |
        pip install --upgrade pip
        pip install -r services/nlp_api/deployment/requirements.txt
        pip install pytest

    - name: test
      working-directory: services/nlp_api
      run: |
        python -m pytest test/
  
  deploy:
    runs-on: ubuntu-latest

    needs:
    - test

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: build
      working-directory: services/nlp_api
      run: |
        docker build -t nlp_alp -f deployment/dockerfile .

    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: build and push
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
    
    - name: build
      working-directory: services/nlp_api
      run: |
        docker build \
          -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/nlp_api:${{ github.sha }} \
          -f deployment/dockerfile .
        docker push \
          ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/nlp_api:${{ github.sha }}