name: test

on:
  push:
    branches:
    - master
    paths:
    - '**/*.py'
    - '.github/workflows/test.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: install dependencies
      run: |
        pip install --upgrade pip
        pip install -r services/nlp_api/deployment/requirements.txt
        pip install pytest

    - name: test
      working-directory: services/nlp_api
      run: |
        python -m pytest test/